<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/testengine.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/jquery.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/solving.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/autoresize.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/support.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/result.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/ajax.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/edit.js"></script>
<script type="text/javascript" src= "<?php echo $GLOBALS['baseurl']; ?>js/startup.js"></script>
